### PR TITLE
ECS

### LINKED ISSUE #1: Bower install (use ember install instead of npm install)
```
Error: ENOENT, no such file or directory '/tmp/build-ember-cli-selectize-0-5-2-ember-1-13-15/tmp/concat_with_maps-input_base_path-V9elLVbJ.tmp/0/bower_components/selectize/dist/js/standalone/selectize.js' 
 at Object.fs.openSync (fs.js:439:18) 
 at Object.fs.readFileSync (fs.js:290:15) 
 at SourceMap.addFile (/var/task/ember-blueprints/1.13.15/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:69:31) 
 at /var/task/ember-blueprints/1.13.15/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat.js:96:14 
 at Array.forEach (native) 
 at ConcatWithMaps.build (/var/task/ember-blueprints/1.13.15/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat.js:94:22) 
 at /var/task/ember-blueprints/1.13.15/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:152:21 
 at lib$rsvp$$internal$$tryCatch (/var/task/ember-blueprints/1.13.15/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16) 
 at lib$rsvp$$internal$$invokeCallback (/var/task/ember-blueprints/1.13.15/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17) 
 at lib$rsvp$$internal$$publish (/var/task/ember-blueprints/1.13.15/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1019:11) 
2016-03-10T17:00:59.136Z    9e58fc73-e6e1-11e5-8993-99dc33446a30    Replacing app name... 
2016-03-10T17:00:59.136Z    9e58fc73-e6e1-11e5-8993-99dc33446a30    Error: { [Error: ENOENT, open '/tmp/ember-cli-selectize-0-5-2-ember-1-13-15/addons.js'] errno: 34, code: 'ENOENT', path: '/tmp/ember-cli-selectize-0-5-2-ember-1-13-15/addons.js' } 
```

### PR DESCRIPTION
**Pull request by joostdevries**
**Work in progress**

Use a Docker/ECS based approach where the build runs in a container. Each ember / ember-cli version will have a specific image ready for building. 

Fixes #1 
## Build process
- [x] Request is made to API gateway
- [x] API gateway launces api.js in lambda
- [x] Lamda function resolves actual addon in NPM
- [x] Lamda function checks whether addon is built already
- _Following assumes addon wasn't built yet_
- [x] Lambda creates temporary credentials using [STS AssumeRole](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/STS.html#assumeRole-property) and attach policy which allow S3 upload access to `addons/<ember_version>/<addon>/<addon_version>`
- [x] Lamda creates ECS task with params:
  - `ADDON_NAME`
  - `ADDON_VERSION`
  - `AWS_ACCESS_KEY_ID`
  - `AWS_SECRET_ACCESS_KEY`
  - `AWS_SESSION_TOKEN`
- [x] ECS creates container based on docker image for specific ember version
- [x] Addon is installed in container
- [x] Addon is built in container
- [x] Assets are uploaded from container using temp credentials
## Todo
- [x] Create ECS cluster
- [x] Create ECS task definition
- [ ] Cleanup API code
- [x] Push image to docker hub https://hub.docker.com/r/joostdevries87/ember-twiddle-addon-builder/
- [x] Migrate API gateway to new AWS account
- [x] On build error, attach log

### CODE REVIEW

**Comment by joostdevries** [comment]
New API: https://v55gcng7te.execute-api.us-east-1.amazonaws.com/staging/addon?ember_version=1.13.15&addon=ember-breadcrumbs&addon_version=latest

**Comment by joostdevries** [comment]
@Gaurav0 ^

**Comment by Gaurav0** [comment]
@joostdevries XMLHttpRequest cannot load https://s3.amazonaws.com/ember-twiddle-addons-beta/ember-1.13.15/ember-truth-helpers/1.2.0/addon.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

**Comment by joostdevries** [comment]
@Gaurav0 fixed.

**Pull request merged**
